---
title: "Polls"
author: "Shafi Rubbani"
date: "3/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gt)
library(janitor)
```

## Polls

```{r polls, message=FALSE, echo=FALSE, include=TRUE, warning=FALSE, cache=TRUE}

spain_polls <- read_csv(file = "https://pollofpolls.eu/get/polls/ES-parliament/format/csv") %>% 
  clean_names() %>% 
  gather(pp, psoe, bng, cc, erc, pnveaj, cs, vox, podemos, eh_bildu, pacma, p_de_cat, key = "party", value = "vote")

good_firms <- spain_polls %>% 
  group_by(firm) %>% 
  summarize(number = n()) %>% 
  filter(number >= 40) %>% 
  pull(firm)

top_parties <- spain_polls %>% 
  group_by(party) %>% 
  summarize(avg_vote = mean(vote, na.rm = TRUE)) %>% 
  arrange(desc(avg_vote)) %>% 
  slice(1:5) %>% 
  pull(party)

spain_polls %>%
  filter(Sys.Date() - date < 365) %>% 
  filter(firm %in% good_firms) %>% 
  filter(party %in% top_parties) %>% 
  ggplot(aes(x = date, y = vote, color = party)) + 
  geom_smooth(se = FALSE) + 
  geom_jitter() +
  labs(x = "Date", y = "Percentage Support", color = "Party") #+
  #scale_color_manual(labels = c("Ciudadanos",
                               #"Unidos Podemos",
                               #"Partido Popular",
                               #"Partido Socialista Obrero Español",
                               #"Vox"))
```